"""empty message

迁移 ID: 4184a6a150e9
父迁移: c2cbe27dd921
创建时间: 2026-01-28 18:46:39.550343

"""
from __future__ import annotations

import json
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, table

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = '4184a6a150e9'
down_revision: str | Sequence[str] | None = 'c2cbe27dd921'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return

    # 定义表结构
    content_table = table('nonebot_plugin_perithacus_content',
        column('id', sa.Integer),
        column('content', sa.Text)  # 根据实际数据类型调整
    )

    # 获取数据库连接
    connection = op.get_bind()

    # 查询所有记录
    result = connection.execute(
        sa.select(content_table.c.id, content_table.c.content)
    ).fetchall()

    # 遍历每条记录，更新content列
    for row in result:
        try:
            content_data = json.loads(row.content)
            if isinstance(content_data, dict) and 'media' in content_data:
                # 删除media字段
                del content_data['media']

                # 更新数据库中的记录
                connection.execute(
                    content_table.update()
                    .where(content_table.c.id == row.id)
                    .values(content=json.dumps(content_data, ensure_ascii=False))
                )
        except (json.JSONDecodeError, TypeError):
            # 如果不是有效的JSON，跳过这条记录
            continue


    # 第二步：处理 nonebot_plugin_perithacus_index 表
    index_table = table('nonebot_plugin_perithacus_index',
        column('id', sa.Integer),
        column('keyword', sa.Text),
        column('alias', sa.Text)
    )

    # 查询 index 表的所有记录
    index_result = connection.execute(
        sa.select(index_table.c.id, index_table.c.keyword, index_table.c.alias)
    ).fetchall()

    # 遍历每条记录，更新 keyword 和 alias 列
    for row in index_result:
        updated_keyword = None
        updated_alias = None

        # 处理 keyword 列
        try:
            keyword_data = json.loads(row.keyword)
            if isinstance(keyword_data, dict) and 'media' in keyword_data:
                # 删除 media 字段
                del keyword_data['media']
                updated_keyword = json.dumps(keyword_data, ensure_ascii=False)
        except (json.JSONDecodeError, TypeError):
            # 如果不是有效的 JSON，跳过这条记录
            pass

        # 处理 alias 列
        try:
            alias_data = json.loads(row.alias)
            if isinstance(alias_data, list):
                # 对列表中的每个元素进行处理
                updated_alias_list = []
                for item in alias_data:
                    if isinstance(item, dict) and 'media' in item:
                        # 删除 media 字段
                        item_without_media = {k: v for k, v in item.items() if k != 'media'}
                        updated_alias_list.append(item_without_media)
                    else:
                        updated_alias_list.append(item)

                updated_alias = json.dumps(updated_alias_list, ensure_ascii=False)
        except (json.JSONDecodeError, TypeError):
            # 如果不是有效的 JSON，跳过这条记录
            pass

        # 更新数据库中的记录（如果有变化）
        update_values = {}
        if updated_keyword is not None:
            update_values['keyword'] = updated_keyword
        if updated_alias is not None:
            update_values['alias'] = updated_alias

        if update_values:
            connection.execute(
                index_table.update()
                .where(index_table.c.id == row.id)
                .values(**update_values)
            )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
