"""empty message

迁移 ID: cc658325e0ad
父迁移: 59488f45afb7
创建时间: 2025-12-03 10:35:28.395309

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cc658325e0ad'
down_revision: str | Sequence[str] | None = '59488f45afb7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_perithacus_index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_method', sa.String(length=8), nullable=False, comment='匹配方式'))
        batch_op.add_column(sa.Column('is_random', sa.Boolean(), nullable=False, comment='是否随机回复'))
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(timezone=True), nullable=False, comment='词条编辑时间戳'))
        batch_op.add_column(sa.Column('date_create', sa.DateTime(timezone=True), nullable=False, comment='词条创建时间戳'))
        batch_op.drop_column('dateModified')
        batch_op.drop_column('dateCreate')
        batch_op.drop_column('matchMethod')
        batch_op.drop_column('isRandom')

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_perithacus_index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isRandom', sa.BOOLEAN(), server_default=sa.text('(TRUE)'), nullable=False))
        batch_op.add_column(sa.Column('matchMethod', sa.VARCHAR(length=8), server_default=sa.text('("精准")'), nullable=False))
        batch_op.add_column(sa.Column('dateCreate', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('dateModified', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_column('date_create')
        batch_op.drop_column('date_modified')
        batch_op.drop_column('is_random')
        batch_op.drop_column('match_method')

    # ### end Alembic commands ###
